#
###################################
# Site wide configuration
####################################
#
title: tony's blog
email: nexussord@gmail.com
description: tony's blog
url: https://nexussord.github.io/ # the base hostname & protocol for your site
keywords: ["Programming", "Football", "EDM"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Tony Kim
  avatar: profile.png #leonids-logo.png
  job: "한국외국어대학교 재학생"
  bio: "Global Service Manager @ Bitbyte"
  email: nexussord@gmail.com
  disqus-shortname:
  twitter: #username
  facebook:
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nexussord #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: murung_dowon #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
